# -*- coding: utf-8 -*-
{
    'name': 'NC Product MRP',
    'version': '18.0.1.0',
    'category': 'Sales/Sales',
    'summary': 'Product Maximum Retail Price Management',
    'description': """
        This module adds Maximum Retail Price (MRP) field to products
    """,
    'author': 'Nishad',
    'website': '',
    'depends': ['base', 'product', 'point_of_sale','stock'],
    'data': [
        'views/product_template_views.xml',
        'views/stock_move_line_views.xml',
        'views/stock_lot_views.xml',
        'views/stock_move_views.xml',
        'views/payment.xml',
        
    ],
   'assets': {
    'point_of_sale._assets_pos': [
        'nc_product_mrp/static/src/js/lot/lot_popup.js',
        'nc_product_mrp/static/src/js/lot/pos_lot_editListInput.js',
        'nc_product_mrp/static/src/xml/lot/pos_lotEditLine.xml',
        'nc_product_mrp/static/src/xml/screen/whatsapp_button.xml',
        'nc_product_mrp/static/src/js/screen/print_screen.js',
        'nc_product_mrp/static/src/js/pos/pos_order_summary.js',
        'nc_product_mrp/static/src/js/pos/nc_pos_store.js',
        'nc_product_mrp/static/src/js/pos/model/order_model.js',
        'nc_product_mrp/static/src/xml/pos/pos_order_summary.xml',
        'nc_product_mrp/static/src/xml/receipt/receipt_header.xml',
        'nc_product_mrp/static/src/js/receipt/receipt_header.js',
        'nc_product_mrp/static/src/xml/receipt/order_line.xml',
        'nc_product_mrp/static/src/js/pos/pos_order_line.js',
        'nc_product_mrp/static/src/js/pos/model/order_line_model.js',
        'nc_product_mrp/static/src/xml/receipt/pos_receipt.xml',
        'nc_product_mrp/static/src/css/pos_print_style.css',
        'nc_product_mrp/static/src/css/pos_print_footer.css',
        'nc_product_mrp/static/src/lib/JsBarcode.all.min.js',
        'nc_product_mrp/static/src/js/pos/widget/barcode.js',
        'nc_product_mrp/static/src/xml/pos/widget/barcode_template.xml',
        'nc_product_mrp/static/src/js/receipt/receipt_design.js',
        'nc_product_mrp/static/src/xml/pos/navbar.xml',
        'nc_product_mrp/static/src/js/pos/navbar.js',
        'nc_product_mrp/static/src/xml/pos/control_buttons.xml',
        'nc_product_mrp/static/src/js/pos/controlButton.js',
        'nc_product_mrp/static/src/xml/pos/PaymentButton/PaymentButton.xml',
        'nc_product_mrp/static/src/js/pos/PaymentButton/PaymentButton.js',
        'nc_product_mrp/static/src/xml/receipt/orderWidget.xml',
    ],
},
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
